# /lustre1/operation/prodharm/scratch/hm_home/trunk_r17057_update/archive/2021/09/20/06/mbr000/HA40_L50_202109200600_00100_GB
# Native Harmonie grid at 5km resolution
  outgeo%dlon = 5000.
  outgeo%dlat = 5000.
  outgeo%gridtype = 'lambert'
  outgeo%projlat = 52.5
  outgeo%projlat2 = 52.5
  outgeo%south = 42.935
  outgeo%polat = 0.
  outgeo%west = -7.89
  outgeo%polon = 0.
  outgeo%projlon = 0.
  outgeo%nlon = 395
  outgeo%nlat = 395
