# /lustre1/operation/prodharm/scratch/hm_home/trunk_r17057_update/archive/2021/09/20/06/mbr000/HA40_L25_202109200600_00100_GB
# Native Harmonie grid at 2.5km 
  outgeo%dlon = 2500.
  outgeo%dlat = 2500.
  outgeo%gridtype = 'lambert'
  outgeo%projlat = 52.5
  outgeo%projlat2 = 52.5
  outgeo%south = 42.935
  outgeo%polat = 0.
  outgeo%west = -7.89
  outgeo%polon = 0.
  outgeo%projlon = 0.
  outgeo%nlon = 789
  outgeo%nlat = 789
